### ISSUE TITLE
这个模型预测结果如何

### ISSUE THREAD

**Issue by wanpixiaozi** [jack139/ETH_predictor_keras_unet#2]
我用模型发现预测结果准确率只有50%多一点，是什么问题啊

**Comment by jack139** [comment]
你能预测到50%多，那说明可以赚钱啊:)。开玩笑的。千万不要用这个做交易，这只是个做着玩的模型。准确率跟很多因素有关，因为价格走势本身就与很多因素有关。如果要进行交易，需要那模型预测结合其他技术分析结合起来进行预测。还有训练数据，如果用去年的交易数据进行训练，跟今年的数据做训练进行对比，你会发现预测结果很不一样。今年币圈疯了。

**Comment by wanpixiaozi** [comment]
多谢，我再看看其他的模型
